### ISSUE TITLE
kebab drop down menus now broken

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-runtime-console#108]
there's no drop down menu - clicking the kebab (3 vertical dots) doesn't drop down the action menu on any page any more (builds/buildconfigs/deployments/pods etc)

<img width="1536" alt="fabric8_runtime_console_and___devtools-platform_-_rh-devtools_mattermost_and_jstrachan_on_freenode_irc_network_ __fabric8__220_users____nt_" src="https://cloud.githubusercontent.com/assets/30140/24010284/56e8e320-0a6f-11e7-8a14-2234cc1af4f4.png">

**Comment by dlabrecq** [comment]
I looking at the main branch for the runtime console, following the latest readme instructions, and running the devshift sample environment. However, I don't see any information when I login, just a blank page.

![screen shot 2017-03-17 at 11 34 52 am](https://cloud.githubusercontent.com/assets/17481322/24050627/cc60b95c-0b05-11e7-9e34-0cfe36020990.png)

I then fired up the planner UI, but I still don't see what's shown in the screenshot above. For example, the code bases page just contains a broken image.

![screen shot 2017-03-17 at 11 35 54 am](https://cloud.githubusercontent.com/assets/17481322/24050653/e8b54e60-0b05-11e7-8738-3fabe32bf33f.png)

**Comment by joshuawilson** [comment]
@dlabrecq it should be in the first image you posted. I'll work with you offline to get it to display data.

**Comment by jstrachan** [comment]
@dlabrecq I wonder if you try running fabric8-runtime-console first and seeing if we can fix the kebab menus there first? It looks from the menu bar like thats the fabric8-ui?

if you run:
```
source environments/devshift-cluster.sh
./caddy.sh
```

then your `fabric8-runtime-console` should point to the devshift cluster and hopefully in the `openshift-tenant` space you should see some builds / environments / pipelines etc
