### ISSUE TITLE
navigating from the list of spaces to a space seems to fail to load resources 

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-runtime-console#127]
a new bug has crept in; maybe due to version upgrades?

Eg if you use the devshift cluster and start at the home page & select 'online-tenant' space then no projects are shown. Hit reload and they are displayed!

It seems the BuildConfigStore loads from 'default' rather that the new namespace

**Comment by pmuir** [comment]
I noticed that too

**Comment by joshuawilson** [comment]
I found a bug in buildconfig, maybe that will fix it.

**Comment by pmuir** [comment]
Yep, there is even a compile error in buildconfig

**Comment by joshuawilson** [comment]
let me know if my fix in buildconfig fixed this issue

**Comment by jstrachan** [comment]
The only compiler error I now see is related to `ENV` in `./src/app/environment.ts` but I still see the issue. Will try debug it soon...

**Comment by jstrachan** [comment]
Its looking like a timing issue between the ActiveRoute.params Observable updating the namespace parameter and the APIs being loaded which is triggering the loading of the buildConfigs (using the old default namespace). Experimenting with some RxJS stuff to join on the two things instead...

**Comment by jstrachan** [comment]
whoah that was a bit harder than I thought to fix ;). So there was a timing issue on the observable event of the NamespaceScope's namespace change on the ActiveRoute; but there was another issue where errors on websockets we causing the events found via a GET to be hidden (when we join the GET with websocket events for real time updates). Hopefully its sorted now though
