### ISSUE TITLE
websockets no longer work using the CORS proxy

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-runtime-console#141]
I wonder if we can avoid using the CORS proxy for websocket URLs? Seems they all fail now in development. They may well fail in docker too when using nginx?

**Comment by pmuir** [comment]
Already done I think. Checking I didn't screw up somewhere.

**Comment by pmuir** [comment]
Yes, wss is going direct to tsrv. I suspect you need to re source environments/devshift-cluster.sh @jstrachan as I moved some env vars around.
