### ISSUE TITLE
Animations seem to flash

### ISSUE THREAD

**Issue by pmuir** [fabric8-ui/fabric8-runtime-console#152]
Not sure what is up here, but they fill in, then clear, then fill in again.

**Comment by jstrachan** [comment]
this on Chrome? Seems OK here. There's a loading animation and a running animation though

**Comment by jstrachan** [comment]
I just reused the animation CSS from OpenShift's current console. TBH I'm not sold on any animation for completed/failed builds - though do love the 'building' animation! ;)

**Comment by pmuir** [comment]
Here is a video of the issue https://screencast.com/t/t5TJ2Ee599

The stages that are completed should not be animated anymore and the stage that is running is going too fast if you compare to the openshift console.

**Comment by jstrachan** [comment]
FWIW this seems fixed now when I tried using fabric8-ui with master of fabric8-runtime-console

**Comment by jstrachan** [comment]
ignore me - they are back for sure - have a pipelines view with one pipeline flashing and one not - am wondering if they all incorrectly flash if the build is not completed yet - just having a look...
