### ISSUE TITLE
the recent kebab menu fix has broken the kubernetes resource picker

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-runtime-console#163]
am sure its just some markup change is required or something?  e.g. see the contents of the drop down menu now appears below the button & the drop down button doesn't do anything (the top left below "Deployments")

<img width="1038" alt="fabric8_runtime_console" src="https://cloud.githubusercontent.com/assets/30140/24146070/f0e775da-0e2b-11e7-8577-2dd83a825d87.png">

BTW the code for viewing the kubernetes resource picker is here: https://github.com/fabric8-ui/fabric8-runtime-console/tree/master/src/app/kubernetes/components/resource-header

**Comment by dlabrecq** [comment]
Yes, I just saw it. This particular menu didn't show up while I was testing changes. I'll attempt to fix it.

**Comment by jstrachan** [comment]
@dlabrecq no worries - thanks!

**Comment by dlabrecq** [comment]
ResourceHeaderComponent is not declared in its component module. This is declared a couple levels up in a common module. Simply needed to import the correct DropdownModule there instead.

**Comment by jstrachan** [comment]
@dlabrecq ah cool thanks - want me to try fix it or are you about to try a PR?

**Comment by jstrachan** [comment]
@dlabrecq that worked a treat - lemme submit a PR

**Comment by dlabrecq** [comment]
I actually have a PR in the works. Just give me a sec.

**Comment by dlabrecq** [comment]
See PR https://github.com/fabric8-ui/fabric8-runtime-console/pull/165

**Comment by jstrachan** [comment]
ah cool thanks!
