### ISSUE TITLE
Environments not displaying

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-runtime-console#217]
While reviewing this PR https://github.com/fabric8-ui/fabric8-runtime-console/pull/215

I clicked the staging link to see it run on the platform. I then logged in, created a new space, went to the space, and went to the environments tab.  I got the following message.

`Something went wrong your environments as the OpenShift Project 'josh-6' is not accessible to you or does not exist.`

![openshift web console](https://cloud.githubusercontent.com/assets/1184371/24506576/f38283dc-152b-11e7-8418-ab2a034dea21.png)

![env-error](https://cloud.githubusercontent.com/assets/1184371/24506594/ff364880-152b-11e7-9c4f-9d7704a34a1e.png)

**Comment by pmuir** [comment]
This needs to be filed against fabric8-ui
