### ISSUE TITLE
Space styles are causing css conflicts

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-runtime-console#219]
The CSS changes in https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/src/app/kubernetes/ui/space/view-page/view-page.space.component.scss do not appear to be encapsulated are causing conflicts with the base PatternFly card styles in the Spaces Homepage ([in progress](https://github.com/mindreeper2420/fabric8-ui/tree/spaces-overview)).

**Comment by pmuir** [comment]
Fixed by  https://github.com/fabric8io/fabric8-ui/pull/400
