### ISSUE TITLE
should the Environments page (maybe we call it 'Resources'?) - be a bit more lazy loading?

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-runtime-console#456]
I wonder rather than loading every kind of resource in all environments on startup if its maybe better to lazily load the resources as folks expand the tree?

So we start the page just watching the spaces/environments; then if folks expand, say, `Deployments` in one of the environments we lazily `listAndWatch` that resource kind. Then folks get to look anywhere they want; but they only pay the IO / wait time for what they want to look at?

**Comment by jstrachan** [comment]
relates to #253 as if we make it lazy loading then we'd need to remove the counters from the tree titles

**Comment by jstrachan** [comment]
@pmuir what do you think? might make it easier to make this page snappy then?

**Comment by pmuir** [comment]
+1 Though we still want to be able to load counts....

**Comment by jstrachan** [comment]
yeah - maybe we only show counts after we've loaded it?

**Comment by jstrachan** [comment]
here's a PR that makes things lazily loaded
https://github.com/fabric8-ui/fabric8-runtime-console/pull/469
