### ISSUE TITLE
CSS issue on the Runtime tab

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-runtime-console#91]
can't see the resource kind drop down
![cssfail](https://cloud.githubusercontent.com/assets/30140/23956559/ddcbeae4-0994-11e7-8b6b-632095255760.png)

**Comment by jstrachan** [comment]
I think this may be a similar issue #89

**Comment by dgutride** [comment]
fixed by: https://github.com/fabric8-ui/fabric8-runtime-console/pull/92 - closing
