### ISSUE TITLE
a common fabric8-ui and fabric8-runtime-console approach to configuration?

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-runtime-console#95]
* fabric8-runtime-console runs stand alone, uses standard OAuth to OpenShift and needs to know the API server & needs to detect/be configured if its in openshift or not
* fabric8-ui uses keycloak/almighty but still needs the OSO API server location

In both cases there's some environment configuration that needs to be loaded into the client. Right now in fabric8-runtime-console we're using a separate REST call on startup to load this file https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/src/config/oauth.json in this code https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/src/app/kubernetes/store/oauth-config-store.ts#L56

It would be nice to settle on a unified approach to this environmental configuration. 

It does complicate the app a reasonable amount not being able to know this configuration on startup. I wonder if we should bake this configuration into the index.html file (so that its a template served up by the server side putting in all the environmental data ASAP) so that all the configuration is loaded before the app bootstraps? So maybe a webpack/template thingy might simplify the code & the app and boost the startup time?

**Comment by jstrachan** [comment]
@pmuir I wonder if you had any thoughts on this - you mentioned doing or having similar ideas around webpack?

**Comment by jstrachan** [comment]
after talking on Chat - its clear how to do this now ;) webpack env vars FTW.

Though not sure yet how we can actually inject real env vars from the server side yet; we seem to be baking them all in at docker build time

**Comment by pmuir** [comment]
@jstrachan we took the approach that at runtime we use patterns to change urls

So for example if we are running at prod-preview.openshift.io the WIT API is at api.prod-preview.openshift.io, bayesian is at recommender.api.prod-preview.openshift.io. I can extend this approach for any env vars that have patterns to them

**Comment by jstrachan** [comment]
@pmuir thanks. Thats great for URIs for endpoints we control. 

It doesn't much help for discovering things like where OpenShift decides to expose the OAuth Authorization URL on OSO, the OAuth Issuer & user scope to use in authentication.

So I think for fabric8-runtime-console the simplest thing might be to add something like this to index.html at the top of the `<body>`:
```html
 <script src="config/env.js"></script>
```
we can then use a template in caddy/nginx to generate the `config/env.js` file to setup all the real runtime env variables in some `window.FABRIC8_ENV` object which we can look in when trying to resolve env vars - or something like that

**Comment by jstrachan** [comment]
I'm hoping for `fabric8-ui` we don't need any/many actual environment variables though

**Comment by pmuir** [comment]
@jstrachan this is what I did in fabric8-ui

https://github.com/fabric8io/fabric8-ui/pull/306

I can port it here easily once we get the right nginx container with the cors proxy in it.

**Comment by jstrachan** [comment]
@pmuir awesome thanks!
